env:
	browser: true
	es2021: true

extends:
	- plugin:react/recommended
	- airbnb
	- prettier

parser: @typescript-eslint/parser

parserOptions:
	ecmaVersion: 12
	project: tsconfig.json
	sourceType: module
	ecmaFeatures:
    jsx: true

plugins: 
	- react
	- @typescript-eslint
	- prettier

rules:
	prettier/prettier: error
	no-use-before-define: off
	react/jsx-props-no-spreading: off
	no-tabs: [ error, { allowIndentationTabs: true } ],
	react/jsx-filename-extension: [ 1, { extensions: [ .js, .ts, .tsx ] }	],
	import/extensions: [
		error,
		ignorePackages,
		{ 
			js: never,
			ts: never,
			tsx: never
		}
	]

settings:
	import/resolver: { 
		node: { 
			extensions: [
				.js,
				.ts,
				.tsx
			] 
		} 
	},
	react: { version: detect }